export const metadata = {
  title: 'DropNotas',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/logoDrm.png" /> 
      </head>
      <body style={{overflow:"hidden"}}>{children}</body>
    </html>
  )
}
